/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "mux4_1.v:1" *)
module mux4_1(I0, I1, I2, I3, sel, y);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "mux4_1.v:2" *)
  input I0;
  (* src = "mux4_1.v:3" *)
  input I1;
  (* src = "mux4_1.v:4" *)
  input I2;
  (* src = "mux4_1.v:5" *)
  input I3;
  (* src = "mux4_1.v:6" *)
  input [1:0] sel;
  (* src = "mux4_1.v:7" *)
  output y;
  function [0:0] _4_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "mux4_1.v:14|mux4_1.v:10" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _4_ = b[0:0];
      4'b??1?:
        _4_ = b[1:1];
      4'b?1??:
        _4_ = b[2:2];
      4'b1???:
        _4_ = b[3:3];
      default:
        _4_ = a;
    endcase
  endfunction
  assign y = _4_(1'hx, { I0, I1, I2, I3 }, { _3_, _2_, _1_, _0_ });
  assign _0_ = sel == (* full_case = 32'd1 *) (* src = "mux4_1.v:14|mux4_1.v:10" *) 2'h3;
  assign _1_ = sel == (* full_case = 32'd1 *) (* src = "mux4_1.v:13|mux4_1.v:10" *) 2'h2;
  assign _2_ = sel == (* full_case = 32'd1 *) (* src = "mux4_1.v:12|mux4_1.v:10" *) 2'h1;
  assign _3_ = ! (* full_case = 32'd1 *) (* src = "mux4_1.v:11|mux4_1.v:10" *) sel;
endmodule
