/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "and_gate.v:1" *)
module and_gate(A, B, Y);
  (* src = "and_gate.v:2" *)
  input A;
  (* src = "and_gate.v:3" *)
  input B;
  (* src = "and_gate.v:4" *)
  output Y;
  assign Y = A & (* src = "and_gate.v:6" *) B;
endmodule
